#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3
ENV_FILE=.env.local

# Modo sem navegador: o wizard so exibe o link; quem abre e o humano.
show_url() { printf '  ↗ abra no navegador: %s\n' "$1"; }

# Guards run before any write_env/set_secret. Values are validated by shape only;
# they are never echoed.
guard_url() {
  local url="$1"
  if [[ -z "${url//[[:space:]]/}" ]]; then
    warn "URL do projeto vazia - nada foi gravado. Cole o Project URL completo."
    exit 1
  fi
  if [[ "$url" != "https://"*.supabase.co ]]; then
    warn "URL do projeto nao parece https://<ref>.supabase.co - confira e rode de novo."
    exit 1
  fi
}

guard_key() {
  local value="$1" lower
  if [[ -z "${value//[[:space:]]/}" ]]; then
    warn "Chave vazia - nada foi gravado. Copie a Publishable/anon key."
    exit 1
  fi
  lower="${value,,}"
  if [[ "$lower" == *service_role* || "$lower" == sb_secret_* ]]; then
    warn "Chave privilegiada detectada (service_role / sb_secret_) - nunca envie esse tipo. Use publishable/anon."
    exit 1
  fi
  # JWT legado (chave anon antiga): header.payload.signature. Decodifica só o payload
  # (nunca a assinatura), com base64 -d do coreutils, padrão em Git Bash/Ubuntu, e
  # rejeita se o payload reivindicar service_role. Tokens anon reais saem intactos.
  local payload_b64 payload_json mod
  if [[ "$value" == *.*.* ]]; then
    payload_b64="${value#*.}"
    payload_b64="${payload_b64%%.*}"
    payload_b64="${payload_b64//-/+}"
    payload_b64="${payload_b64//_//}"
    mod=$(( ${#payload_b64} % 4 ))
    if (( mod == 2 )); then payload_b64="${payload_b64}=="
    elif (( mod == 3 )); then payload_b64="${payload_b64}="
    fi
    payload_json=$(printf '%s' "$payload_b64" | base64 -d 2>/dev/null || true)
    if [[ "${payload_json,,}" == *service_role* ]]; then
      warn "JWT legado com role service_role detectado no payload - nunca envie esse tipo. Use publishable/anon."
      exit 1
    fi
  fi
}

banner "Ticket 06: Supabase project + Data API credentials"

# ── Stage 1: create the project and apply supabase/schema.sql ─────────────
stage "Supabase: create project + apply schema"
say "We'll create the project and run the schema so public.tasks exists."
show_url "https://supabase.com/dashboard/new/"
step "Sign in, pick an organisation, name the project (e.g. tasks-slip), set a database password you can remember, choose a region and click Create new project."
pause "Wait for the project to finish provisioning (green checkmark)."
step "Open the new project, then SQL Editor (left sidebar) > New query."
step "Paste the ENTIRE contents of supabase/schema.sql from this repo and click Run."
step "It must report success (table public.tasks created, policies created)."
if ! confirm "Did the schema run successfully?"; then
  warn "Schema nao confirmado - nada foi gravado. Aplique supabase/schema.sql e rode o wizard de novo."
  exit 1
fi

# ── Stage 2: capture the Data API URL and the publishable/anon key ────────
stage "Supabase: capture Data API URL + Publishable key"
say "Both are captured hidden so nothing echoes to the terminal."
show_url "https://supabase.com/dashboard/"
step "Open the tasks-slip project, then Project Settings > API (or Connect > Data API)."
step "Copy the Project URL (https://REFERENCE.supabase.co) and paste it below."
ask_secret VITE_SUPABASE_URL "Paste the project URL:"
step "In the same page (Settings > API Keys or Connect): copy the Publishable key (sb_publishable_...)."
say "If no Publishable key is shown, copy the legacy anon key (eyJhbGciOi...)."
step "Never use the secret key or service_role key -- only publishable/anon."
ask_secret VITE_SUPABASE_ANON_KEY "Paste the publishable/anon key:"
guard_url "$VITE_SUPABASE_URL"
guard_key "$VITE_SUPABASE_ANON_KEY"

# ── Stage 3: persist locally (.env.local) and to GitHub secrets ───────────
stage "Persist .env.local + GitHub secrets"
say "Values land in .env.local (git-ignored) and as the two CI secrets the Pages workflow reads."
write_env VITE_SUPABASE_URL "$VITE_SUPABASE_URL"
write_env VITE_SUPABASE_ANON_KEY "$VITE_SUPABASE_ANON_KEY"
set_secret VITE_SUPABASE_URL "$VITE_SUPABASE_URL"
set_secret VITE_SUPABASE_ANON_KEY "$VITE_SUPABASE_ANON_KEY"
# ──────────────────────────────────────────────────────────────────────────

finish
