#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

APP_URL="https://laginho.github.io/slip/"
TICKET=".scratch/polish-and-publish/issues/07-validate-installs.md"
[[ -f "$TICKET" ]] || { warn "rode a partir da raiz do repo (não achei $TICKET)"; exit 1; }

# resultado PASS/FAIL + nota por etapa
verdict() { # verdict VAR "pergunta de sucesso"
  local var="$1" question="$2" notes=""
  if confirm "$question"; then printf -v "$var" 'PASS'; else printf -v "$var" 'FAIL'; fi
  ask "${var}_NOTES" "Alguma observação? (Enter para nenhuma)"
}

banner "Ticket 07 — validar instalações standalone do slip"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Windows: instalar o app"
say "Vamos instalar o slip como app standalone no Windows."
open_url "$APP_URL"
step "No Edge ou Chrome, clique no ícone de instalar na barra de endereço"
step "  (Edge: 'Instalar Slip' · Chrome: monitor com seta para baixo)."
step "Se não houver ícone: menu ⋯/⋮ → Apps → 'Instalar este site como um aplicativo'."
step "Confirme a instalação e feche a aba do navegador."
step "Abra o app pelo menu Iniciar (procure 'slip')."
say  "Verifique: entrada no menu Iniciar, janela própria, SEM barra de endereço/abas."
verdict WIN_INSTALL "Instalou e abre standalone (janela própria, sem chrome de navegador)?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Windows: funcionar offline"
say "Agora o teste offline, com o app instalado FECHADO."
step "Desligue a rede: clique no ícone de rede na bandeja → desative Wi-Fi"
step "  (ou ative o Modo avião)."
step "Abra o app slip pelo menu Iniciar."
step "Confirme que a lista aparece, e crie + complete uma task de teste."
step "Religue a rede e confirme que a task de teste sincroniza (aparece no site)."
verdict WIN_OFFLINE "Funcionou por completo offline e sincronizou ao religar?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Android: instalar o app"
say "Agora no celular. Abra este endereço no Chrome do Android:"
say ""
say "  ${BOLD}${APP_URL}${RESET}"
say ""
step "No Chrome: menu ⋮ → 'Adicionar à tela inicial' → 'Instalar'"
step "  (ou o banner/opção 'Instalar app', se aparecer)."
step "Abra pelo ícone novo na tela inicial."
say  "Verifique: ícone próprio no launcher, janela própria, sem barra do Chrome."
verdict ANDROID_INSTALL "Instalou e abre standalone no Android?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Android: funcionar offline"
step "Feche o app no celular."
step "Ative o Modo avião."
step "Abra o app pelo ícone e confirme que a lista aparece e dá para criar task."
step "Desative o Modo avião e confirme que sincronizou."
verdict ANDROID_OFFLINE "Funcionou em modo avião e sincronizou depois?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Windows: autostart no login + iniciar minimizado"
say "A spec prometeu isso como 'alcançável, não confirmado' — hora de provar."
say ""
say "Primeiro, o caminho nativo do browser:"
step "Edge: abra edge://apps → clique no slip → procure o toggle de"
step "  'Iniciar automaticamente' no login.  Chrome: chrome://apps →"
step "  clique direito no slip → 'Iniciar app ao fazer login'."
say ""
if confirm "O browser oferece autostart E uma opção de iniciar minimizado?"; then
  AUTOSTART_METHOD="nativo do browser (autostart + minimizado)"
  say "Ótimo — deixe ligado. Melhor caso confirmado."
else
  say ""
  say "Sem 'iniciar minimizado' nativo — aplicando o fallback documentado:"
  step "Se ligou o autostart nativo acima, DESLIGUE (evita abrir duas vezes)."
  step "Win+R → digite  shell:startup  → Enter (abre a pasta Inicializar)."
  step "Menu Iniciar → ache o slip → clique direito → 'Abrir local do arquivo'"
  step "  e COPIE o atalho para a pasta Inicializar."
  step "No atalho copiado: clique direito → Propriedades → Executar:"
  step "  'Minimizada' → OK."
  AUTOSTART_METHOD="fallback: atalho em shell:startup com Executar: Minimizada"
  warn "PWAs Chromium às vezes ignoram 'Minimizada' — o reboot dirá."
fi
ask AUTOSTART_NOTES "Alguma observação? (Enter para nenhuma)"
say ""
warn "A verificação final exige um reboot/login real. Faça depois que o wizard"
warn "terminar e confira: o app abriu sozinho? minimizado?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Registrar resultados no ticket"
RESULTS="
### Validação $(date +%F) (via setup-ticket-07.sh)

- Windows install standalone: ${WIN_INSTALL}${WIN_INSTALL_NOTES:+ — ${WIN_INSTALL_NOTES}}
- Windows offline: ${WIN_OFFLINE}${WIN_OFFLINE_NOTES:+ — ${WIN_OFFLINE_NOTES}}
- Android install standalone: ${ANDROID_INSTALL}${ANDROID_INSTALL_NOTES:+ — ${ANDROID_INSTALL_NOTES}}
- Android offline: ${ANDROID_OFFLINE}${ANDROID_OFFLINE_NOTES:+ — ${ANDROID_OFFLINE_NOTES}}
- Autostart: ${AUTOSTART_METHOD}${AUTOSTART_NOTES:+ — ${AUTOSTART_NOTES}} — verificação por reboot: pendente ao fim do wizard
"
say "Vai ser adicionado ao ticket:"
printf '%s\n' "$RESULTS" | sed 's/^/  /'
if confirm "Gravar em $TICKET?"; then
  grep -q '^## Comments' "$TICKET" || printf '\n## Comments\n' >> "$TICKET"
  printf '%s\n' "$RESULTS" >> "$TICKET"
  say "${GREEN}✓ registrado${RESET} em $TICKET"
else
  warn "não gravado — anote os resultados manualmente no ticket"
fi
# ──────────────────────────────────────────────────────────────────────────

finish
note "Falta só: reboot/login para verificar o autostart. Depois do reboot, avise"
note "o Claude o resultado para fechar as checkboxes do ticket."
